### ISSUE TITLE
API Errors: Server 500

### ISSUE THREAD

**Issue by williamthowe** [agilecrm/php-api#14]
HI there,

Just intergraded with your API via this PHP wrapper - which was pretty straight forward thanks. However I have had at least 4 server 500 responses like so:

> GuzzleHttp\Exception\ServerException: Server error: `PUT XXXX/dev/api/contacts/edit-properties` resulted in a `500 Internal Server Error` response

It does seem to be just that particular API call currently.
 
This seems to happen every week presently which is a problem because I am setting tags against new and current records which trigger campaigns and obviously some people are falling through.

I'm trying to catch more info and will send it when I have it, but a 500 is internal on your server so not much I can say really. Can you please look at better error handling for this and I'm happy to feed it back to you as I see it my side.

Cheers,

**Comment by graut** [comment]
Hi @williamthowe ,

This 500 server error can be possible due to wrong format of data (chunk data) you are sending to Agile CRM.

Can you please send mail to below mentioned mail IDs.
care@agilecrm.com , kiran@agilecrm.com, ghanshyam@agilecrm.com

Please send mail with details like 

1. Your Agile CRM domain
2. Contact JSON data for  PUT XXXX/dev/api/contacts/edit-properties

As soon as you will send mail we will work on it and reply you.

Thanks

**Comment by tobz-nz** [comment]
We figured out the problem - some of our stored Agile ID's were not being saved correctly (a BIGINT field does not seem to be suffice).

A little feedback - this was an issue on our end and so we'd expect a 400 error(probably a 422) not a 500.
Also, a JSON response would be better than html for an API :)
I assume this is an uncaught exception - try adding a catch for negative numbers to your id validation... 
I fact I better check that too. I mean who sends a negative ID anyway ;)
